services:
  - type: worker
    name: trading-bot
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install setuptools==65.5.0 wheel==0.38.4
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: CHECK_INTERVAL
        value: "15"
      - key: TOP_COINS_COUNT
        value: "10"
      - key: PYTHON_VERSION
        value: "3.11.7"
