services:
  - type: web
    name: crypto-trading-bot
    runtime: python
    pythonVersion: "3.10"  # تغيير مهم!
    buildCommand: |
      python -m pip install --upgrade pip==23.3.1 setuptools==68.0.0 wheel==0.41.2
      pip install -r requirements.txt
    startCommand: python bot_service.py
    envVars:
      - key: COINEX_ACCESS_ID
        value: your_coinex_access_id
      - key: COINEX_SECRET_KEY
        value: your_coinex_secret_key
      - key: TELEGRAM_TOKEN
        value: your_telegram_token
      - key: TELEGRAM_CHAT_ID
        value: your_chat_id
