services:
  - type: web
    name: crypto-trading-bot
    runtime: python
    pythonVersion: "3.10"  # استخدم 3.10 بدلاً من 3.13
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python bot_service.py
    envVars:
      - key: COINEX_ACCESS_ID
        value: your_coinex_access_id
      - key: COINEX_SECRET_KEY
        value: your_coinex_secret_key
      - key: TELEGRAM_TOKEN
        value: your_telegram_token
      - key: TELEGRAM_CHAT_ID
        value: your_chat_id
