services:
  - type: web
    name: crypto-trading-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python map.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: COINEX_ACCESS_ID
        valueFromGroup: coinex_api
      - key: COINEX_SECRET_KEY
        valueFromGroup: coinex_api
      - key: TELEGRAM_TOKEN
        valueFromGroup: telegram
      - key: TELEGRAM_CHAT_ID
        valueFromGroup: telegram