services:
  - type: web
    name: crypto-trading-bot
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python bot_service.py >> bot.log 2>&1
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
      - key: COINEX_ACCESS_ID
        value: your_coinex_access_id
      - key: COINEX_SECRET_KEY
        value: your_coinex_secret_key
      - key: TELEGRAM_TOKEN
        value: your_telegram_token
      - key: TELEGRAM_CHAT_ID
        value: your_chat_id
